on: [push, workflow_dispatch]

name: Trigger pbp patch workflow

jobs: 
  trigger:
    name: trigger_pbp_patch
    runs-on: ubuntu-latest
    env: 
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.NFLVERSE_GH_TOKEN }}
    steps:
      - name: Trigger pbp patch
        run: | 
          gh api repos/nflverse/nflverse-pbp/actions/workflows/35258014/dispatches -f ref='main'
        
